#!/bin/bash

# Create simple placeholder PNGs using base64 data
# 16x16 blue square
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVR42mNgYGD4z0AE+M8ABGAAKQNkCkxVDAwMDKgYGBgYGBgYGBgYGBgYGBgYAADNwgH94AFKwgAAAABJRU5ErkJggg==" | base64 -d > icon16.png

# 48x48 blue square
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAOklEQVR42u3OMQEAAAjDMPr/aBFNYvzKSwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvg4NBwN+AAHx8QAAAABJRU5ErkJggg==" | base64 -d > icon48.png

# 128x128 blue square  
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAASklEQVR42u3OMQEAAAjDMPr/aBFNYvzKSwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA3BwcDfgAB8fEAAAAASUVORK5CYII=" | base64 -d > icon128.png

echo "Icons created successfully!"
ls -lh *.png
